version: '3'
services:

  db:
    image: "redis:alpine"
    hostname: redis       # host name in the RestWebService application
    ports:
     - "6379:6379"        
     
  rest-web-service:
    build: ./RestWebService
    ports: 
      - 8181:8080
    links:
      - "db:redis"
      
  presentation:
    image: php:apache
    volumes: 
      - ./presentation:/var/www/html  # unable html updating without restarting docker compose
    ports:
      - 8282:80          # use http://localhost:8282/ in a web browser
